services:
  postgres:
    image: postgres:16
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness_pw
      POSTGRES_DB: fitnessdb
    ports:
      - "5432:5432"
    volumes:
      - fitness_pg_data:/var/lib/postgresql/data
volumes:
  fitness_pg_data:
